src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $libelle = null;

    #[ORM\Column]
    private ?float $ageMini = null;

    #[ORM\Column]
    private ?float $ageMaxi = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heureDebut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heureFin = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Type $type = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Jour $jour = null;

    /**
     * @var Collection<int, inscription>
     */
    #[ORM\OneToMany(targetEntity: Inscription::class, mappedBy: 'cours')]
    private Collection $inscription;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Professeur $professeur = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeInstrument $typeInstrument = null;

    public function __construct()
    {
        $this->inscription = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getAgeMini(): ?float
    {
        return $this->ageMini;
    }

    public function setAgeMini(float $ageMini): static
    {
        $this->ageMini = $ageMini;

        return $this;
    }

    public function getAgeMaxi(): ?float
    {
        return $this->ageMaxi;
    }

    public function setAgeMaxi(float $ageMaxi): static
    {
        $this->ageMaxi = $ageMaxi;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getHeureDebut(): ?\DateTime
    {
        return $this->heureDebut;
    }

    public function setHeureDebut(\DateTime $heureDebut): static
    {
        $this->heureDebut = $heureDebut;

        return $this;
    }

    public function getHeureFin(): ?\DateTime
    {
        return $this->heureFin;
    }

    public function setHeureFin(\DateTime $heureFin): static
    {
        $this->heureFin = $heureFin;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeNom(): ?string
    {
        return $this->type?->getNom();
    }

    public function getJour(): ?Jour
    {
        return $this->jour;
    }

    public function setJour(?Jour $jour): static
    {
        $this->jour = $jour;

        return $this;
    }

    public function getJourLibelle(): ?string
    {
        return $this->jour?->getLibelle();
    }

    /**
     * @return Collection<int, inscription>
     */
    public function getInscription(): Collection
    {
        return $this->inscription;
    }

    public function addInscription(Inscription $inscription): static
    {
        if (!$this->inscription->contains($inscription)) {
            $this->inscription->add($inscription);
            $inscription->setCours($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): static
    {
        if ($this->inscription->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getCours() === $this) {
                $inscription->setCours(null);
            }
        }

        return $this;
    }

    public function getProfesseur(): ?Professeur
    {
        return $this->professeur;
    }

    public function setProfesseur(?Professeur $professeur): static
    {
        $this->professeur = $professeur;

        return $this;
    }

    public function getProfesseurNom(): ?string
    {
        return $this->professeur?->getNom();
    }

    public function getTypeInstrument(): ?TypeInstrument
    {
        return $this->typeInstrument;
    }

    public function setTypeInstrument(?TypeInstrument $typeInstrument): static
    {
        $this->typeInstrument = $typeInstrument;

        return $this;
    }

    public function getTypeInstrumentLibelle(): ?string
    {
        return $this->typeInstrument?->getLibelle();
    }
}

src/Form/CoursType.php
<?php

namespace App\Form;

use App\Entity\Cours;
use App\Entity\Jour;
use App\Entity\Professeur;
use App\Entity\Type;
use App\Entity\TypeInstrument;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('ageMini')
            ->add('ageMaxi')
            ->add('nbPlaces')
            ->add('heureDebut')
            ->add('heureFin')
            ->add('type', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'nom',
            ])
            ->add('jour', EntityType::class, [
                'class' => Jour::class,
                'choice_label' => 'libelle',
            ])
            ->add('professeur', EntityType::class, [
                'class' => Professeur::class,
                'choice_label' => 'nom',
            ])
            ->add('typeInstrument', EntityType::class, [
                'class' => TypeInstrument::class,
                'choice_label' => 'libelle',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cours::class,
        ]);
    }
}

src/Controller/CoursController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Form\CoursType;
use App\Repository\CoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/cours')]
final class CoursController extends AbstractController
{
    #[Route(name: 'app_cours_index', methods: ['GET'])]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('cours/index.html.twig', [
            'cours' => $coursRepository->findBy(['type' => 2]),
        ]);
    }

    #[Route('/new', name: 'app_cours_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cour = new Cours();
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cour);
            $entityManager->flush();

            return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cours/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_show', methods: ['GET'])]
    public function show(Cours $cour): Response
    {
        return $this->render('cours/show.html.twig', [
            'cour' => $cour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('cours/edit.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_delete', methods: ['POST'])]
    public function delete(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($cour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_cours_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cours/_delete_form.html.twig
<form method="post" action="{{ path('app_cours_delete', {'id': cour.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/cours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">
        {{ button_label|default('Sauvegarder') }}
    </button>
{{ form_end(form) }}

templates/cours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cours{% endblock %}

{% block body %}
    <h1>Modifier un cours</h1>

    {{ include('cours/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('app_cours_index') }}" class="btn btn-secondary">
        Retour à la liste
    </a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}

templates/cours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours index{% endblock %}

{% block body %}
<style>
div{
  margin-left: 20px;
}
</Style>
<div>
    <center><h1>Liste des cours</h1>
    <h5>Si aucun cours ne vous convient, prenez un cours particulier.</h5>
    <a href="http://localhost/emusic/public/reserverCours">Réserver</a></center>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle</th>
                <th>AgeMini</th>
                <th>AgeMaxi</th>
                <th>NbPlaces</th>
                <th>HeureDebut</th>
                <th>HeureFin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% if cours is not empty %}
            {% for cour in cours %}
              <tr>
                <td>{{ cour.id }}</td>
                <td>{{ cour.libelle }}</td>
                <td>{{ cour.ageMini }}</td>
                <td>{{ cour.ageMaxi }}</td>
                <td>{{ cour.nbPlaces }}</td>
                <td>{{ cour.heureDebut ? cour.heureDebut|date('H:i') : '' }}</td>
                <td>{{ cour.heureFin ? cour.heureFin|date('H:i') : '' }}</td>
                <td>
                    <a href="{{ path('app_cours_show', {'id': cour.id}) }}">Afficher</a>
                     | 
                    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}">Modifier</a>
                </td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="8">Aucun cours pour cet instrument</td>
            </tr>
          {% endif %}
        </tbody>
    </table>
     <a href="{{ path('app_cours_new') }}" class="btn btn-primary">
        Créer un nouveau cours
    </a>
</div>
{% endblock %}

templates/cours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cours{% endblock %}

{% block body %}
    <h1>Créer un nouveau cours</h1>

    {{ include('cours/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

    <a href="{{ path('app_cours_index') }}" class="btn btn-secondary">
        Retour à la liste
    </a>
{% endblock %}

templates/cours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours{% endblock %}

{% block body %}
    <h1>Cours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cour.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ cour.libelle }}</td>
            </tr>
            <tr>
                <th>AgeMini</th>
                <td>{{ cour.ageMini }}</td>
            </tr>
            <tr>
                <th>AgeMaxi</th>
                <td>{{ cour.ageMaxi }}</td>
            </tr>
            <tr>
                <th>NbPlaces</th>
                <td>{{ cour.nbPlaces }}</td>
            </tr>
            <tr>
                <th>HeureDebut</th>
                <td>{{ cour.heureDebut ? cour.heureDebut|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>HeureFin</th>
                <td>{{ cour.heureFin ? cour.heureFin|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Enseignant</th>
                <td>{{ cour.professeurNom }}</td>
            </tr>
            <tr>
                <th>Jour</th>
                <td>{{ cour.jourLibelle }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ cour.typeNom }}</td>
            </tr>
            <tr>
                <th>Instrument</th>
                <td>{{ cour.typeInstrumentLibelle }}</td>
            </tr>
        </tbody>
    </table>
    <a href="http://localhost/emusic/public/reserverCours">Reserver</a>

    <a href="{{ path('app_cours_index') }}" class="btn btn-secondary">Retour à la liste</a>
    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}" class="btn btn-primary">Modifier</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}